name: Laravel CI

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build & Push to Docker Hub
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t $DOCKER_USERNAME/$DOCKER_REPO:latest .
          docker push $DOCKER_USERNAME/$DOCKER_REPO:latest
          docker tag $DOCKER_USERNAME/$DOCKER_REPO:latest $DOCKER_USERNAME/$DOCKER_REPO:${TIMESTAMP}
          docker push $DOCKER_USERNAME/$DOCKER_REPO:${TIMESTAMP}