name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, exif, pcntl, bcmath, mysql

    - name: Install Composer dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist || composer update --no-ansi --no-interaction --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate application key
      run: php artisan key:generate

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h"127.0.0.1" --silent; do
          echo 'waiting for mysql to be connectable...'
          sleep 1
        done

    - name: Configure MySQL
      run: |
        mysql --user=root --password=root --host=127.0.0.1 --execute="CREATE DATABASE ecommerce_db;"
        mysql --user=root --password=root --host=127.0.0.1 --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
      env:
        MYSQL_ALLOW_EMPTY_PASSWORD: no

    - name: Run migrations
      env:
          DB_CONNECTION: mysql
          DB_DATABASE: ecommerce_db
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: ecommerce_db
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
      run: php artisan test
